version: '3.8'
services:
  app:
    build: .
    container_name: msh-app
    ports:
      - '3000:3000'
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://msh-mongo:27017/msh-db
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:7-alpine
    container_name: msh-redis
    ports:
      - '6379:6379'

  mongo:
    image: mongo:6
    container_name: msh-mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db

  kafka:
    image: apache/kafka:4.3.1
    container_name: msh-kafka
    ports:
      - "9092:9092"
